/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AnonymousElectionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createElection"
      | "decryptionCallback"
      | "elections"
      | "endElection"
      | "finalizeElection"
      | "getDecryptedVoteSum"
      | "getElection"
      | "getElectionCount"
      | "getEncryptedVoteSum"
      | "hasUserVoted"
      | "hasVoted"
      | "protocolId"
      | "vote"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ElectionCreated"
      | "ElectionEnded"
      | "ElectionFinalized"
      | "FinalizeRequested"
      | "VoteCasted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createElection",
    values: [string, string, string[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "decryptionCallback",
    values: [BigNumberish, BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "elections",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "endElection",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeElection",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDecryptedVoteSum",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getElection",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getElectionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedVoteSum",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasUserVoted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createElection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decryptionCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "elections", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "endElection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeElection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDecryptedVoteSum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getElection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getElectionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedVoteSum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasUserVoted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
}

export namespace ElectionCreatedEvent {
  export type InputTuple = [
    electionId: BigNumberish,
    title: string,
    admin: AddressLike
  ];
  export type OutputTuple = [electionId: bigint, title: string, admin: string];
  export interface OutputObject {
    electionId: bigint;
    title: string;
    admin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ElectionEndedEvent {
  export type InputTuple = [electionId: BigNumberish];
  export type OutputTuple = [electionId: bigint];
  export interface OutputObject {
    electionId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ElectionFinalizedEvent {
  export type InputTuple = [
    electionId: BigNumberish,
    decryptedSum: BigNumberish
  ];
  export type OutputTuple = [electionId: bigint, decryptedSum: bigint];
  export interface OutputObject {
    electionId: bigint;
    decryptedSum: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FinalizeRequestedEvent {
  export type InputTuple = [electionId: BigNumberish, requestId: BigNumberish];
  export type OutputTuple = [electionId: bigint, requestId: bigint];
  export interface OutputObject {
    electionId: bigint;
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastedEvent {
  export type InputTuple = [electionId: BigNumberish, voter: AddressLike];
  export type OutputTuple = [electionId: bigint, voter: string];
  export interface OutputObject {
    electionId: bigint;
    voter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AnonymousElection extends BaseContract {
  connect(runner?: ContractRunner | null): AnonymousElection;
  waitForDeployment(): Promise<this>;

  interface: AnonymousElectionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createElection: TypedContractMethod<
    [
      _title: string,
      _description: string,
      _candidateNames: string[],
      _durationInHours: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  decryptionCallback: TypedContractMethod<
    [requestId: BigNumberish, cleartexts: BytesLike, arg2: BytesLike[]],
    [boolean],
    "nonpayable"
  >;

  elections: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        string,
        string,
        bigint,
        bigint
      ] & {
        title: string;
        description: string;
        candidateCount: bigint;
        endTime: bigint;
        isActive: boolean;
        isFinalized: boolean;
        encryptedVoteSum: string;
        admin: string;
        totalVoters: bigint;
        decryptedSum: bigint;
      }
    ],
    "view"
  >;

  endElection: TypedContractMethod<
    [_electionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  finalizeElection: TypedContractMethod<
    [_electionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getDecryptedVoteSum: TypedContractMethod<
    [_electionId: BigNumberish],
    [bigint],
    "view"
  >;

  getElection: TypedContractMethod<
    [_electionId: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        string[],
        bigint,
        boolean,
        boolean,
        string,
        bigint
      ] & {
        title: string;
        description: string;
        candidateCount: bigint;
        candidateNames: string[];
        endTime: bigint;
        isActive: boolean;
        isFinalized: boolean;
        admin: string;
        totalVoters: bigint;
      }
    ],
    "view"
  >;

  getElectionCount: TypedContractMethod<[], [bigint], "view">;

  getEncryptedVoteSum: TypedContractMethod<
    [_electionId: BigNumberish],
    [string],
    "view"
  >;

  hasUserVoted: TypedContractMethod<
    [_electionId: BigNumberish, _voter: AddressLike],
    [boolean],
    "view"
  >;

  hasVoted: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  vote: TypedContractMethod<
    [
      _electionId: BigNumberish,
      _encryptedVote: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createElection"
  ): TypedContractMethod<
    [
      _title: string,
      _description: string,
      _candidateNames: string[],
      _durationInHours: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "decryptionCallback"
  ): TypedContractMethod<
    [requestId: BigNumberish, cleartexts: BytesLike, arg2: BytesLike[]],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "elections"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        string,
        string,
        bigint,
        bigint
      ] & {
        title: string;
        description: string;
        candidateCount: bigint;
        endTime: bigint;
        isActive: boolean;
        isFinalized: boolean;
        encryptedVoteSum: string;
        admin: string;
        totalVoters: bigint;
        decryptedSum: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "endElection"
  ): TypedContractMethod<[_electionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "finalizeElection"
  ): TypedContractMethod<[_electionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getDecryptedVoteSum"
  ): TypedContractMethod<[_electionId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getElection"
  ): TypedContractMethod<
    [_electionId: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        string[],
        bigint,
        boolean,
        boolean,
        string,
        bigint
      ] & {
        title: string;
        description: string;
        candidateCount: bigint;
        candidateNames: string[];
        endTime: bigint;
        isActive: boolean;
        isFinalized: boolean;
        admin: string;
        totalVoters: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getElectionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEncryptedVoteSum"
  ): TypedContractMethod<[_electionId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "hasUserVoted"
  ): TypedContractMethod<
    [_electionId: BigNumberish, _voter: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [
      _electionId: BigNumberish,
      _encryptedVote: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ElectionCreated"
  ): TypedContractEvent<
    ElectionCreatedEvent.InputTuple,
    ElectionCreatedEvent.OutputTuple,
    ElectionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ElectionEnded"
  ): TypedContractEvent<
    ElectionEndedEvent.InputTuple,
    ElectionEndedEvent.OutputTuple,
    ElectionEndedEvent.OutputObject
  >;
  getEvent(
    key: "ElectionFinalized"
  ): TypedContractEvent<
    ElectionFinalizedEvent.InputTuple,
    ElectionFinalizedEvent.OutputTuple,
    ElectionFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "FinalizeRequested"
  ): TypedContractEvent<
    FinalizeRequestedEvent.InputTuple,
    FinalizeRequestedEvent.OutputTuple,
    FinalizeRequestedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCasted"
  ): TypedContractEvent<
    VoteCastedEvent.InputTuple,
    VoteCastedEvent.OutputTuple,
    VoteCastedEvent.OutputObject
  >;

  filters: {
    "ElectionCreated(uint256,string,address)": TypedContractEvent<
      ElectionCreatedEvent.InputTuple,
      ElectionCreatedEvent.OutputTuple,
      ElectionCreatedEvent.OutputObject
    >;
    ElectionCreated: TypedContractEvent<
      ElectionCreatedEvent.InputTuple,
      ElectionCreatedEvent.OutputTuple,
      ElectionCreatedEvent.OutputObject
    >;

    "ElectionEnded(uint256)": TypedContractEvent<
      ElectionEndedEvent.InputTuple,
      ElectionEndedEvent.OutputTuple,
      ElectionEndedEvent.OutputObject
    >;
    ElectionEnded: TypedContractEvent<
      ElectionEndedEvent.InputTuple,
      ElectionEndedEvent.OutputTuple,
      ElectionEndedEvent.OutputObject
    >;

    "ElectionFinalized(uint256,uint256)": TypedContractEvent<
      ElectionFinalizedEvent.InputTuple,
      ElectionFinalizedEvent.OutputTuple,
      ElectionFinalizedEvent.OutputObject
    >;
    ElectionFinalized: TypedContractEvent<
      ElectionFinalizedEvent.InputTuple,
      ElectionFinalizedEvent.OutputTuple,
      ElectionFinalizedEvent.OutputObject
    >;

    "FinalizeRequested(uint256,uint256)": TypedContractEvent<
      FinalizeRequestedEvent.InputTuple,
      FinalizeRequestedEvent.OutputTuple,
      FinalizeRequestedEvent.OutputObject
    >;
    FinalizeRequested: TypedContractEvent<
      FinalizeRequestedEvent.InputTuple,
      FinalizeRequestedEvent.OutputTuple,
      FinalizeRequestedEvent.OutputObject
    >;

    "VoteCasted(uint256,address)": TypedContractEvent<
      VoteCastedEvent.InputTuple,
      VoteCastedEvent.OutputTuple,
      VoteCastedEvent.OutputObject
    >;
    VoteCasted: TypedContractEvent<
      VoteCastedEvent.InputTuple,
      VoteCastedEvent.OutputTuple,
      VoteCastedEvent.OutputObject
    >;
  };
}
