/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FHEKeyManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_VALIDITY_PERIOD"
      | "admin"
      | "currentKeyId"
      | "deactivateKey"
      | "emergencyKeyRotation"
      | "extendKeyValidity"
      | "getCurrentKey"
      | "getKeyInfo"
      | "getTotalKeyRotations"
      | "isKeyValid"
      | "keyRotations"
      | "keyValidations"
      | "rotateKey"
      | "transferAdmin"
      | "validateKeyCompatibility"
      | "validateVote"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EmergencyKeyRotation"
      | "KeyDeactivated"
      | "KeyRotated"
      | "KeyValidated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_VALIDITY_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "currentKeyId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateKey",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyKeyRotation",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "extendKeyValidity",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentKey",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getKeyInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalKeyRotations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isKeyValid",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "keyRotations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "keyValidations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rotateKey",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validateKeyCompatibility",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validateVote",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_VALIDITY_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentKeyId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyKeyRotation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "extendKeyValidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getKeyInfo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTotalKeyRotations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isKeyValid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "keyRotations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "keyValidations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rotateKey", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateKeyCompatibility",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateVote",
    data: BytesLike
  ): Result;
}

export namespace EmergencyKeyRotationEvent {
  export type InputTuple = [keyId: BigNumberish, emergencyKey: BytesLike];
  export type OutputTuple = [keyId: bigint, emergencyKey: string];
  export interface OutputObject {
    keyId: bigint;
    emergencyKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KeyDeactivatedEvent {
  export type InputTuple = [keyId: BigNumberish, deactivatedBy: AddressLike];
  export type OutputTuple = [keyId: bigint, deactivatedBy: string];
  export interface OutputObject {
    keyId: bigint;
    deactivatedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KeyRotatedEvent {
  export type InputTuple = [
    keyId: BigNumberish,
    publicKey: BytesLike,
    rotatedBy: AddressLike
  ];
  export type OutputTuple = [
    keyId: bigint,
    publicKey: string,
    rotatedBy: string
  ];
  export interface OutputObject {
    keyId: bigint;
    publicKey: string;
    rotatedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KeyValidatedEvent {
  export type InputTuple = [keyId: BigNumberish, isValid: boolean];
  export type OutputTuple = [keyId: bigint, isValid: boolean];
  export interface OutputObject {
    keyId: bigint;
    isValid: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FHEKeyManager extends BaseContract {
  connect(runner?: ContractRunner | null): FHEKeyManager;
  waitForDeployment(): Promise<this>;

  interface: FHEKeyManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_VALIDITY_PERIOD: TypedContractMethod<[], [bigint], "view">;

  admin: TypedContractMethod<[], [string], "view">;

  currentKeyId: TypedContractMethod<[], [bigint], "view">;

  deactivateKey: TypedContractMethod<
    [_keyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  emergencyKeyRotation: TypedContractMethod<
    [_emergencyKey: BytesLike],
    [void],
    "nonpayable"
  >;

  extendKeyValidity: TypedContractMethod<
    [_keyId: BigNumberish, _additionalPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;

  getCurrentKey: TypedContractMethod<
    [],
    [
      [string, bigint, bigint, boolean] & {
        publicKey: string;
        keyId: bigint;
        validityPeriod: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getKeyInfo: TypedContractMethod<
    [_keyId: BigNumberish],
    [
      [bigint, string, boolean, bigint, string] & {
        rotationTime: bigint;
        publicKey: string;
        isActive: boolean;
        validityPeriod: bigint;
        rotatedBy: string;
      }
    ],
    "view"
  >;

  getTotalKeyRotations: TypedContractMethod<[], [bigint], "view">;

  isKeyValid: TypedContractMethod<[_keyId: BigNumberish], [boolean], "view">;

  keyRotations: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, boolean, bigint, string] & {
        rotationTime: bigint;
        publicKey: string;
        privateKeyHash: string;
        isActive: boolean;
        validityPeriod: bigint;
        rotatedBy: string;
      }
    ],
    "view"
  >;

  keyValidations: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [boolean, bigint, string] & {
        isValid: boolean;
        lastValidationTime: bigint;
        validationHash: string;
      }
    ],
    "view"
  >;

  rotateKey: TypedContractMethod<
    [_newPublicKey: BytesLike, _privateKeyHash: BytesLike],
    [void],
    "nonpayable"
  >;

  transferAdmin: TypedContractMethod<
    [_newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  validateKeyCompatibility: TypedContractMethod<
    [_keyId: BigNumberish, _dataHash: BytesLike],
    [boolean],
    "view"
  >;

  validateVote: TypedContractMethod<
    [_encryptedVote: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_VALIDITY_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "currentKeyId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deactivateKey"
  ): TypedContractMethod<[_keyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyKeyRotation"
  ): TypedContractMethod<[_emergencyKey: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "extendKeyValidity"
  ): TypedContractMethod<
    [_keyId: BigNumberish, _additionalPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCurrentKey"
  ): TypedContractMethod<
    [],
    [
      [string, bigint, bigint, boolean] & {
        publicKey: string;
        keyId: bigint;
        validityPeriod: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getKeyInfo"
  ): TypedContractMethod<
    [_keyId: BigNumberish],
    [
      [bigint, string, boolean, bigint, string] & {
        rotationTime: bigint;
        publicKey: string;
        isActive: boolean;
        validityPeriod: bigint;
        rotatedBy: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalKeyRotations"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isKeyValid"
  ): TypedContractMethod<[_keyId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "keyRotations"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, boolean, bigint, string] & {
        rotationTime: bigint;
        publicKey: string;
        privateKeyHash: string;
        isActive: boolean;
        validityPeriod: bigint;
        rotatedBy: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "keyValidations"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [boolean, bigint, string] & {
        isValid: boolean;
        lastValidationTime: bigint;
        validationHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "rotateKey"
  ): TypedContractMethod<
    [_newPublicKey: BytesLike, _privateKeyHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferAdmin"
  ): TypedContractMethod<[_newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "validateKeyCompatibility"
  ): TypedContractMethod<
    [_keyId: BigNumberish, _dataHash: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "validateVote"
  ): TypedContractMethod<[_encryptedVote: BytesLike], [boolean], "view">;

  getEvent(
    key: "EmergencyKeyRotation"
  ): TypedContractEvent<
    EmergencyKeyRotationEvent.InputTuple,
    EmergencyKeyRotationEvent.OutputTuple,
    EmergencyKeyRotationEvent.OutputObject
  >;
  getEvent(
    key: "KeyDeactivated"
  ): TypedContractEvent<
    KeyDeactivatedEvent.InputTuple,
    KeyDeactivatedEvent.OutputTuple,
    KeyDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "KeyRotated"
  ): TypedContractEvent<
    KeyRotatedEvent.InputTuple,
    KeyRotatedEvent.OutputTuple,
    KeyRotatedEvent.OutputObject
  >;
  getEvent(
    key: "KeyValidated"
  ): TypedContractEvent<
    KeyValidatedEvent.InputTuple,
    KeyValidatedEvent.OutputTuple,
    KeyValidatedEvent.OutputObject
  >;

  filters: {
    "EmergencyKeyRotation(uint256,bytes32)": TypedContractEvent<
      EmergencyKeyRotationEvent.InputTuple,
      EmergencyKeyRotationEvent.OutputTuple,
      EmergencyKeyRotationEvent.OutputObject
    >;
    EmergencyKeyRotation: TypedContractEvent<
      EmergencyKeyRotationEvent.InputTuple,
      EmergencyKeyRotationEvent.OutputTuple,
      EmergencyKeyRotationEvent.OutputObject
    >;

    "KeyDeactivated(uint256,address)": TypedContractEvent<
      KeyDeactivatedEvent.InputTuple,
      KeyDeactivatedEvent.OutputTuple,
      KeyDeactivatedEvent.OutputObject
    >;
    KeyDeactivated: TypedContractEvent<
      KeyDeactivatedEvent.InputTuple,
      KeyDeactivatedEvent.OutputTuple,
      KeyDeactivatedEvent.OutputObject
    >;

    "KeyRotated(uint256,bytes32,address)": TypedContractEvent<
      KeyRotatedEvent.InputTuple,
      KeyRotatedEvent.OutputTuple,
      KeyRotatedEvent.OutputObject
    >;
    KeyRotated: TypedContractEvent<
      KeyRotatedEvent.InputTuple,
      KeyRotatedEvent.OutputTuple,
      KeyRotatedEvent.OutputObject
    >;

    "KeyValidated(uint256,bool)": TypedContractEvent<
      KeyValidatedEvent.InputTuple,
      KeyValidatedEvent.OutputTuple,
      KeyValidatedEvent.OutputObject
    >;
    KeyValidated: TypedContractEvent<
      KeyValidatedEvent.InputTuple,
      KeyValidatedEvent.OutputTuple,
      KeyValidatedEvent.OutputObject
    >;
  };
}
